# Generated by Django 6.0.6 on 2026-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_placeimage_places_plac_orderin_746292_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
